/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gurukul;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author prashant
 */
public class All_students extends javax.swing.JFrame {

    /**
     * Creates new form All_students
     */
    public All_students() {
        initComponents();
        
         this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("academic.png")));
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gurukul : All Students");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1523, 29, 224, 523);

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setOpaque(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 70, 1517, 523);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gurupng/print-3x.png"))); // NOI18N
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 30, 110, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gurupng/reload-3x.png"))); // NOI18N
        jButton1.setText("Refresh");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 30, 120, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gurupng/arrow-circle-left-3x.png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(140, 30, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gurukul/bg.jpg"))); // NOI18N
        jLabel1.setAlignmentX(1.0F);
        jLabel1.setAlignmentY(1.0F);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1, 1, 1920, 1200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        
         
        ResultSet Results;
      
        
         //create query
    String q ="select * from entry";
      
        try 
        {
            
             
                Db_bean db=new Db_bean();
                
                
            //creating statement for query perform
            Results= db.show(q);
           
        jTable1.setModel(DbUtils.resultSetToTableModel(Results));
            
         } catch (SQLException ex) {
              //  Logger.getLogger(login_page.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showInternalMessageDialog(this,ex.getMessage());
            } catch (ClassNotFoundException ex) {
            //Logger.getLogger(Find.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showInternalMessageDialog(this,ex.getMessage());
        } 
           
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        ResultSet Results;
      
        
         //create query
    String q ="select * from entry";
      
        try 
        {
            
             
                Db_bean db=new Db_bean();
                
                
            //creating statement for query perform
            Results= db.show(q);
           
        jTable1.setModel(DbUtils.resultSetToTableModel(Results));
            
         } catch (SQLException ex) {
              //  Logger.getLogger(login_page.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showInternalMessageDialog(this,ex.getMessage());
            } catch (ClassNotFoundException ex) {
            //Logger.getLogger(Find.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showInternalMessageDialog(this,ex.getMessage());
        } 
                   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
      
            try {
                boolean action=jTable1.print();
            } catch (PrinterException ex) {
                Logger.getLogger(All_students.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Options s=new Options();
       s.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
         ResultSet Results;
      
        
         //create query
    String q ="select * from entry";
      
        try 
        {
            
             
                Db_bean db=new Db_bean();
                
                
            //creating statement for query perform
            Results= db.show(q);
          
      jTable1.setModel(DbUtils.resultSetToTableModel(Results));
       //jTable1.setModel(DbUtils.resultSetToTableModel(Results));     
         } catch (SQLException ex) {
              //  Logger.getLogger(login_page.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showInternalMessageDialog(this,ex.getMessage());
            } catch (ClassNotFoundException ex) {
            //Logger.getLogger(Find.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showInternalMessageDialog(this,ex.getMessage());
        } 
                   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
       Options s=new Options();
       s.setVisible(true);
       this.setVisible(false);

    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
      
      
            try {
                boolean action=jTable1.print();
            } catch (PrinterException ex) {
                Logger.getLogger(All_students.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jButton2KeyPressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
       ResultSet Results;
      
        
         //create query
    String q ="select * from entry";
      
        try 
        {
            
             
                Db_bean db=new Db_bean();
                
                
            //creating statement for query perform
            Results= db.show(q);
           
        jTable1.setModel(DbUtils.resultSetToTableModel(Results));
            
         } catch (SQLException ex) {
              //  Logger.getLogger(login_page.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showInternalMessageDialog(this,ex.getMessage());
            } catch (ClassNotFoundException ex) {
            //Logger.getLogger(Find.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showInternalMessageDialog(this,ex.getMessage());
        } 
                   // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
ResultSet Results;
      
        
         //create query
    String q ="select * from entry";
      
        try 
        {
            
             
                Db_bean db=new Db_bean();
                
                
            //creating statement for query perform
            Results= db.show(q);
           
        jTable1.setModel(DbUtils.resultSetToTableModel(Results));
            
         } catch (SQLException ex) {
              //  Logger.getLogger(login_page.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showInternalMessageDialog(this,ex.getMessage());
            } catch (ClassNotFoundException ex) {
            //Logger.getLogger(Find.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showInternalMessageDialog(this,ex.getMessage());
        } 
                   // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(All_students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(All_students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(All_students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(All_students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new All_students().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
