/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gurukul;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.lang.invoke.LambdaMetafactory;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;


/**
 *
 * @author Vivek
 */
public class Image_Uploder extends javax.swing.JFrame {

    /**
     * Creates new form Demo
     */
    public Image_Uploder() {
        initComponents();
         this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("academic.png")));
        this.setExtendedState(MAXIMIZED_BOTH);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gurukul Photo Loader");
        getContentPane().setLayout(null);

        jLabel3.setText("Student Name :");
        jLabel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel3ComponentShown(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 60, 92, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(106, 49, 140, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Uploader and Preview"));
        jPanel1.setOpaque(false);

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Demo");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gurupng/arrow-circle-bottom-2x.png"))); // NOI18N
        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gurupng/person-2x.png"))); // NOI18N
        jButton2.setText("save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 122, 370, 290);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gurupng/magnifying-glass-3x.png"))); // NOI18N
        jButton3.setText("Find");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(256, 48, 90, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gurupng/arrow-circle-left-2x.png"))); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 90, 90, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Not Found");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 90, 150, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gurukul/bg.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setAlignmentX(1.0F);
        jLabel5.setAlignmentY(1.0F);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1, 1, 1958, 1200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
if(jLabel4.getText()=="Found")
{
        JFileChooser chooser = new JFileChooser();
 
chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
 
// JFileChooserEx is the name of the JFrameForm/Java class
int res = chooser.showOpenDialog(Image_Uploder.this);
 
if (res == JFileChooser.APPROVE_OPTION) {
 
    File file = chooser.getSelectedFile();      
 
    // Creating ImageIcon out of the selected file
    ImageIcon image = new ImageIcon(file.getAbsolutePath());
    // Get width and height of picLabel
    Rectangle rect =jLabel1.getBounds();
    // Scaling the Image to fit in the picLabel
    Image scaledImage = image.getImage().getScaledInstance(rect.width, rect.height, Image.SCALE_DEFAULT);
    // Converting the image back to ImageIcon to make it acceptable by picLabel
    image = new ImageIcon(scaledImage);      
  
    jLabel1.setIcon(image);      
}
else {
    JOptionPane.showMessageDialog(this, "Dialog cancelled by the user");
}
}
else
{
    JOptionPane.showMessageDialog(this, "Record Not Found");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String sname=jTextField1.getText();
        
         String myname=sname;
       
        Rectangle rec = jLabel1.getBounds();
 
BufferedImage badge = new BufferedImage(rec.width, rec.height,
        BufferedImage.TYPE_INT_ARGB);
 
jLabel1.paint(badge.getGraphics());
 
 String filepath=null;
 File myfile=null;
    try {
        // Writing the captured area to a png image
        String pat=UUID.randomUUID().toString();
        
         // JOptionPane.showMessageDialog(Image_Uploder.this, UUID.randomUUID().toString());
              
          sname=sname+pat;
          //C://Upload/ramc6710ab5-343d-443c-a451-6b6abacd8076.jpg
        myfile=new File("C://upload/",sname+".jpg");
     
        ImageIO.write(badge, "png", myfile);
        JOptionPane.showMessageDialog(Image_Uploder.this, "The Image is Saved Successfully!");
 
          
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(Image_Uploder.this, "Oops! Something gone wrong while saving." + ex.getMessage(),
                "Error!", JOptionPane.ERROR_MESSAGE);
    }

       
   filepath=myfile.getName();
        // String url="jdbc:mysql://localhost:3306/gurukul";
        //String userID="root";
        //String Password="";//
       Statement stmt = null;
        ResultSet Results;
       

      

        try {
            
                Db_bean db=new Db_bean();
         
            //create query

            String q ="update entry set photo='"+filepath+"' where NAME='"+myname+"' ";

          

            int x=db.update(q);
            

            if(x>0)
            {
               
                JOptionPane.showMessageDialog(this,"photo changed");
                new Options().setVisible(true);
                this.setVisible(false);
            }
            else
            {
                 JOptionPane.showMessageDialog(this,"photo not changed"+q);
            }
         } catch (ClassNotFoundException ex) {
            System.out.println("Class not found");

        } catch (SQLException ex) {
            System.out.println("DB Server not found");
             System.out.println(ex.getMessage());
        }
    
    
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
            
     
        String sname=jTextField1.getText();
        //setting jdbc
       
      
        ResultSet Results;
        
      
                

        try {
            
             Db_bean db=new Db_bean();
           
           
            //create query
            String q ="select * from entry where NAME='"+sname+"'";

            //  int s=Integer.parseInt(q);

            Results=db.show(q);

            if(Results.next())
            {
                this.setExtendedState(MAXIMIZED_BOTH);
               jPanel1.show();
                jLabel4.setText("Found");
            
            //   JOptionPane.showMessageDialog(this, "Record Matched");
             

               
            }
            else
            {
                 jLabel4.setText("Not Found");
               JOptionPane.showMessageDialog(this, "Record Not Found");
                 int minimumSize = 0;
               this.setExtendedState(minimumSize);
                 jPanel1.hide();
            }

         
        } catch (ClassNotFoundException ex) {
            System.out.println("Class not found");

        } catch (SQLException ex) {
            System.out.println("DB Server not found");

        }

        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel3ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3ComponentShown

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       Options o=new Options();
       o.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private  void myupload()
    {
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Image_Uploder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Image_Uploder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Image_Uploder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Image_Uploder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Image_Uploder().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
